name: Update Major Version

on:
  release:
    types:
      - released                        # When new version of your action is released
  workflow_dispatch:                    # To run manually on any tag

jobs:
  update-major-version:
    runs-on: ubuntu-latest
    steps:
      - name: Update major version
        uses: sayyid5416/major-tags@v1
